In [15]:
import pandas as pd

In [16]:
record1 = pd.Series({'Name': 'Alice',
                        'Class': 'Physics',
                        'Score': 85})
record2 = pd.Series({'Name': 'Jack',
                        'Class': 'Chemistry',
                        'Score': 82})
record3 = pd.Series({'Name': 'Helen',
                        'Class': 'Biology',
                        'Score': 90})

In [17]:
df = pd.DataFrame([record1, record2, record3],
                  index=['school1', 'school2', 'school3'])
df.head()

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school3  Helen    Biology     90

In [18]:
students = [{'Name': 'Alice',
              'Class': 'Physics',
              'Score': 85},
            {'Name': 'Jack',
             'Class': 'Chemistry',
             'Score': 82},
            {'Name': 'Helen',
             'Class': 'Biology',
             'Score': 90}]

In [19]:
df = pd.DataFrame(students, index=['school1', 'school2', 'school1'])

df.head()

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [ ]:
print(df.loc["school2"]) # Aaccessing Rows

print(type(df.loc["school2"]))

Name          Jack
Class    Chemistry
Score           82
Name: school2, dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
print(df.loc["school1"]) 

print(type(df.loc["school1"]))

          Name    Class  Score
school1  Alice  Physics     85
school1  Helen  Biology     90
<class 'pandas.core.frame.DataFrame'>

In [22]:
df.loc["school1", "Name"]

school1    Alice
school1    Helen
Name: Name, dtype: object

In [ ]:
df.T # Transposing the DataFrame

       school1    school2  school1
Name     Alice       Jack    Helen
Class  Physics  Chemistry  Biology
Score       85         82       90

In [ ]:
df.T.loc["Name"] # Accessing the Columns

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [ ]:
df["Name"] # Accessing Columns Shortcut

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [26]:
df.loc["school1"]["Name"]

school1    Alice
school1    Helen
Name: Name, dtype: object

In [27]:
print(type(df.loc["school1"]["Name"]))
print(type(df.loc["school1"]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [28]:
df.loc[:, ["Name", "Score"]]

          Name  Score
school1  Alice     85
school2   Jack     82
school1  Helen     90

In [29]:
df.drop("school1")

         Name      Class  Score
school2  Jack  Chemistry     82

In [30]:
df

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [31]:
cpydf = df.copy()

# inplace true means real DF will be updated, axis 1 means column and 0 means row
cpydf.drop("Name", inplace=True, axis=1)
cpydf

             Class  Score
school1    Physics     85
school2  Chemistry     82
school1    Biology     90

In [32]:
del cpydf["Class"]
cpydf

         Score
school1     85
school2     82
school1     90

In [33]:
df["ClassRanking"] = None
df

          Name      Class  Score ClassRanking
school1  Alice    Physics     85         None
school2   Jack  Chemistry     82         None
school1  Helen    Biology     90         None