# Pandas DataFrame Data Structure

A **DataFrame** is the core of Pandas. It is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns). You can think of it like a spreadsheet or a SQL table.

This notebook covers:
- Creating DataFrames from Series and Dictionaries
- Querying rows and columns using `.loc`
- Transposing DataFrames
- Manipulating columns (dropping and copying)

In [1]:
# Import the Pandas library
import pandas as pd

## Creating a DataFrame from Multiple Series

You can build a DataFrame by passing a list of `pd.Series` items. Each Series will represent a row. The index of the DataFrame must be provided separately to label these rows.

In [2]:
# Define three separate Series representing three students' records
record1 = pd.Series({'Name': 'Alice',
                        'Class': 'Physics',
                        'Score': 85})
record2 = pd.Series({'Name': 'Jack',
                        'Class': 'Chemistry',
                        'Score': 82})
record3 = pd.Series({'Name': 'Helen',
                        'Class': 'Biology',
                        'Score': 90})

In [3]:
# Create the DataFrame by passing the Series in a list.
# Set custom index names matching the school each student belongs to.
df = pd.DataFrame([record1, record2, record3],
                  index=['school1', 'school2', 'school3'])
df.head()

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school3  Helen    Biology     90

## Creating a DataFrame from a List of Dictionaries

Instead of creating Series objects first, you can directly pass a list of Python dictionaries to initiate the DataFrame.

In [4]:
# Define a list where each element is a dictionary representing a row
students = [{'Name': 'Alice',
              'Class': 'Physics',
              'Score': 85},
            {'Name': 'Jack',
             'Class': 'Chemistry',
             'Score': 82},
            {'Name': 'Helen',
             'Class': 'Biology',
             'Score': 90}]

In [5]:
# Create DataFrame. Note that indices do not have to be unique!
df = pd.DataFrame(students, index=['school1', 'school2', 'school1'])

df.head()

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

## Accessing Rows in a DataFrame

To access a row, use `.loc[]` with the index name. 
- If the index is **unique**, Pandas returns a `Series`.
- If the index is **duplicated**, Pandas returns a subset `DataFrame` containing all matching rows.

In [6]:
# Accessing a row with a unique index returns a Series
print(df.loc["school2"])

print(type(df.loc["school2"]))

Name          Jack
Class    Chemistry
Score           82
Name: school2, dtype: object
<class 'pandas.core.series.Series'>

In [7]:
# Accessing a row with a duplicated index returns a DataFrame
print(df.loc["school1"])

print(type(df.loc["school1"]))

          Name    Class  Score
school1  Alice  Physics     85
school1  Helen  Biology     90
<class 'pandas.core.frame.DataFrame'>

In [8]:
# You can also query a specific row and a specific column simultaneously using `.loc[row, column]`
df.loc["school1", "Name"]

school1    Alice
school1    Helen
Name: Name, dtype: object

## Transposing and Column Access

You can transpose a DataFrame (swap rows and columns) using the `.T` attribute.

In [9]:
# Transpose the DataFrame
df.T

       school1    school2  school1
Name     Alice       Jack    Helen
Class  Physics  Chemistry  Biology
Score       85         82       90

In [10]:
# After transposing, what was originally a column ('Name') is now an index.
df.T.loc["Name"]

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

## Extracting Columns

The standard and most efficient way to access a column in Pandas is using the bracket operator `[]` directly on the DataFrame.

In [11]:
# Direct bracket accessor gets the entire 'Name' column as a Series
df["Name"]

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [12]:
# Chaining operations: first query rows labeled 'school1', then get the 'Name' column from the subset
df.loc["school1"]["Name"]

school1    Alice
school1    Helen
Name: Name, dtype: object

In [13]:
# As seen before, verifying the object types returned
print(type(df.loc["school1"]["Name"]))
print(type(df.loc["school1"]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [14]:
# .loc[rows, columns] allows fetching all rows for multiple specific columns safely
df.loc[:, ["Name", "Score"]]

          Name  Score
school1  Alice     85
school2   Jack     82
school1  Helen     90

## Dropping Data

You can use `.drop()` to remove rows or columns. By default, Pandas operates on an immutable baseline—meaning it doesn't change the original DataFrame unless you explicitly use `inplace=True` or reassign the variable.

In [15]:
# Drop the row labeled 'school1'. 
# This returns a NEW DataFrame without modifying `df`.
df.drop("school1")

         Name      Class  Score
school2  Jack  Chemistry     82

In [16]:
# Printing the original DataFrame proves that 'school1' is still there.
df

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [17]:
# Make a separate copy of the DataFrame
cpydf = df.copy()

# `inplace=True` forces the change to persist in `cpydf`.
# `axis=1` tells Pandas to drop a COLUMN instead of a row.
cpydf.drop("Name", inplace=True, axis=1)
cpydf

             Class  Score
school1    Physics     85
school2  Chemistry     82
school1    Biology     90

In [18]:
# Alternatively, the `del` keyword can be used to permanently remove a column in-place instantly.
del cpydf["Class"]
cpydf

         Score
school1     85
school2     82
school1     90

## Adding New Columns

Adding columns is as simple as defining a new key in a dictionary, using bracket notation.

In [19]:
# Add a new column 'ClassRanking' and set all its values to None to be filled later
df['ClassRanking'] = None
df

          Name      Class  Score ClassRanking
school1  Alice    Physics     85         None
school2   Jack  Chemistry     82         None
school1  Helen    Biology     90         None