# DataFrame Indexing and Loading

This notebook demonstrates how to load tabular data from a CSV file into a Pandas DataFrame and how to manipulate its columns and indices for better readability and accessibility.

In [1]:
# Import Pandas for data processing
import pandas as pd

## Loading Data from a CSV File

Pandas provides highly optimized functions for loading data. The `read_csv` function converts a CSV file into a DataFrame instantly.

In [2]:
# Load the admission predictions dataset from the datasets folder
df = pd.read_csv("datasets/Admission_Predict.csv")

# Display the first 5 rows to understand the tabular structure
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

## Using an Existing Column as the Index

Notice above that Pandas automatically gives us a `0, 1, 2...` baseline index, but the dataset already has a `Serial No.` column. We can tell Pandas to use that column as the Index instead.

In [3]:
# Re-load the CSV, but this time specify `index_col=0` meaning column 0 ('Serial No.') acts as the row index.
df = pd.read_csv("datasets/Admission_Predict.csv", index_col=0)

df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

## Inspecting and Cleaning Column Names

Datasets often contain hidden issues like leading/trailing spaces in column titles. You can inspect your text labels using the `.columns` property.

In [4]:
# Return a list of all column name strings.
# Keep an eye out for trailing spaces (e.g., 'LOR ', 'Chance of Admit ')
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='object')

### Renaming Specific Columns

The `.rename()` function lets you map specific existing names to clean new names.

In [5]:
# Rename 'SOP' to 'Statement of Purpose' and notice the required trailing space in 'LOR '
new_df=df.rename(columns={'SOP': 'Statement of Purpose','LOR ': 'Letter of Recommendation'})
new_df.head()

,GRE Score,TOEFL Score,University Rating,Statement of Purpose,Letter of Recommendation,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

### Bulk Cleaning Strings using Built-in String Manipulation

If many headers have trailing spaces, renaming manually is inefficient. You can use string manipulation methods directly as mappers.

In [6]:
# Pass the standard Python string method str.strip to the mapper. 
# This automatically executes .strip() across all column names.
new_df=new_df.rename(mapper=str.strip, axis='columns')
new_df.head()

,GRE Score,TOEFL Score,University Rating,Statement of Purpose,Letter of Recommendation,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

### Replacing Column Labels entirely

Alternatively, you can extract the columns into a Python list, modify the list using list comprehensions, and assign it back to `df.columns`.

In [7]:
# Extract current columns into a list
cols = list(df.columns)

# Create a new list where each string is uppercase and stripped of whitespace
newCols = [x.upper().strip() for x in cols]

# Hard-replace the DataFrame's columns with the new list
df.columns = newCols
df.head()

,GRE SCORE,TOEFL SCORE,UNIVERSITY RATING,SOP,LOR,CGPA,RESEARCH,CHANCE OF ADMIT
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65