In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("datasets/Admission_Predict.csv", index_col=0)
df.columns = [x.upper().strip() for x in df.columns]

df.head()

,GRE SCORE,TOEFL SCORE,UNIVERSITY RATING,SOP,LOR,CGPA,RESEARCH,CHANCE OF ADMIT
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [4]:
admitMask = df['CHANCE OF ADMIT'] > 0.7
admitMask

Serial No.
1       True
2       True
3       True
4       True
5      False
       ...
396     True
397     True
398     True
399    False
400     True
Name: CHANCE OF ADMIT, Length: 400, dtype: bool

In [5]:
df.where(admitMask).head()

,GRE SCORE,TOEFL SCORE,UNIVERSITY RATING,SOP,LOR,CGPA,RESEARCH,CHANCE OF ADMIT
Serial No.,,,,,,,,
1,337.0,118.0,4.0,4.5,4.5,9.65,1.0,0.92
2,324.0,107.0,4.0,4.0,4.5,8.87,1.0,0.76
3,316.0,104.0,3.0,3.0,3.5,8.00,1.0,0.72
4,322.0,110.0,3.0,3.5,2.5,8.67,1.0,0.80
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.where(admitMask).dropna().head()

,GRE SCORE,TOEFL SCORE,UNIVERSITY RATING,SOP,LOR,CGPA,RESEARCH,CHANCE OF ADMIT
Serial No.,,,,,,,,
1,337.0,118.0,4.0,4.5,4.5,9.65,1.0,0.92
2,324.0,107.0,4.0,4.0,4.5,8.87,1.0,0.76
3,316.0,104.0,3.0,3.0,3.5,8.00,1.0,0.72
4,322.0,110.0,3.0,3.5,2.5,8.67,1.0,0.80
6,330.0,115.0,5.0,4.5,3.0,9.34,1.0,0.90

In [7]:
df[df['CHANCE OF ADMIT'] > 0.7].head()

,GRE SCORE,TOEFL SCORE,UNIVERSITY RATING,SOP,LOR,CGPA,RESEARCH,CHANCE OF ADMIT
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
6,330,115,5,4.5,3.0,9.34,1,0.90

In [8]:
df['GRE SCORE'].head()

Serial No.
1    337
2    324
3    316
4    322
5    314
Name: GRE SCORE, dtype: int64

In [9]:
df[['GRE SCORE', "TOEFL SCORE"]].head()

            GRE SCORE  TOEFL SCORE
Serial No.
1                 337          118
2                 324          107
3                 316          104
4                 322          110
5                 314          103

In [10]:
df[df["GRE SCORE"] > 320].head()

,GRE SCORE,TOEFL SCORE,UNIVERSITY RATING,SOP,LOR,CGPA,RESEARCH,CHANCE OF ADMIT
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
4,322,110,3,3.5,2.5,8.67,1,0.80
6,330,115,5,4.5,3.0,9.34,1,0.90
7,321,109,3,3.0,4.0,8.20,1,0.75

In [12]:
(df["CHANCE OF ADMIT"] > 0.7) & (df["CHANCE OF ADMIT"] > 0.9)

Serial No.
1       True
2      False
3      False
4      False
5      False
       ...
396    False
397    False
398     True
399    False
400     True
Name: CHANCE OF ADMIT, Length: 400, dtype: bool

In [13]:
df["CHANCE OF ADMIT"].gt(0.7) & df["CHANCE OF ADMIT"].lt(0.9)

Serial No.
1      False
2       True
3       True
4       True
5      False
       ...
396     True
397     True
398    False
399    False
400    False
Name: CHANCE OF ADMIT, Length: 400, dtype: bool

In [14]:
df["CHANCE OF ADMIT"].gt(0.7).lt(0.9)

Serial No.
1      False
2      False
3      False
4      False
5       True
       ...
396    False
397    False
398    False
399     True
400    False
Name: CHANCE OF ADMIT, Length: 400, dtype: bool