In [17]:
import pandas as pd

In [18]:
staff_df = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR', 
                          'Location': 'State Street'},
                         {'Name': 'Sally', 'Role': 'Course liasion', 
                          'Location': 'Washington Avenue'},
                         {'Name': 'James', 'Role': 'Grader', 
                          'Location': 'Washington Avenue'}])
student_df = pd.DataFrame([{'Name': 'James', 'School': 'Business', 
                            'Location': '1024 Billiard Avenue'},
                           {'Name': 'Mike', 'School': 'Law', 
                            'Location': 'Fraternity House #22'},
                           {'Name': 'Sally', 'School': 'Engineering', 
                            'Location': '512 Wilson Crescent'}])

In [19]:
staff_df

    Name            Role           Location
0  Kelly  Director of HR       State Street
1  Sally  Course liasion  Washington Avenue
2  James          Grader  Washington Avenue

In [20]:
student_df

    Name       School              Location
0  James     Business  1024 Billiard Avenue
1   Mike          Law  Fraternity House #22
2  Sally  Engineering   512 Wilson Crescent

In [21]:
pd.merge(staff_df, student_df, how="left", on="Name")

    Name            Role         Location_x       School            Location_y
0  Kelly  Director of HR       State Street          NaN                   NaN
1  Sally  Course liasion  Washington Avenue  Engineering   512 Wilson Crescent
2  James          Grader  Washington Avenue     Business  1024 Billiard Avenue

In [22]:
staff_df = pd.DataFrame([{'First Name': 'Kelly', 'Last Name': 'Desjardins', 
                          'Role': 'Director of HR'},
                         {'First Name': 'Sally', 'Last Name': 'Brooks', 
                          'Role': 'Course liasion'},
                         {'First Name': 'James', 'Last Name': 'Wilde', 
                          'Role': 'Grader'}])
student_df = pd.DataFrame([{'First Name': 'James', 'Last Name': 'Hammond', 
                            'School': 'Business'},
                           {'First Name': 'Mike', 'Last Name': 'Smith', 
                            'School': 'Law'},
                           {'First Name': 'Sally', 'Last Name': 'Brooks', 
                            'School': 'Engineering'}])

In [24]:
pd.merge(staff_df, student_df, how='outer', on=['First Name','Last Name'])

  First Name   Last Name            Role       School
0      James     Hammond             NaN     Business
1      James       Wilde          Grader          NaN
2      Kelly  Desjardins  Director of HR          NaN
3       Mike       Smith             NaN          Law
4      Sally      Brooks  Course liasion  Engineering