# Date and Time Functionality

Pandas provides powerful tools for working with dates and times. This notebook covers Timestamps, Periods, DatetimeIndex, and more.

In [1]:
import pandas as pd
import numpy as np

### Timestamps

`pd.Timestamp` represents a single point in time, essentially pandas' equivalent of Python's `datetime`.

In [2]:
pd.Timestamp('9/1/2019 10:05AM')

Timestamp('2019-09-01 10:05:00')

In [3]:
pd.Timestamp(2019, 12, 20, 0, 0)

Timestamp('2019-12-20 00:00:00')

You can access various attributes like year, month, second, or even `isoweekday()`.

In [4]:
pd.Timestamp(2019, 12, 20, 0, 0).isoweekday()

5

In [5]:
pd.Timestamp(2019, 12, 20, 5, 2,23).second

23

### Periods

Unlike a Timestamp, a `pd.Period` represents a specific span of time (e.g., a specific month or day).

In [6]:
pd.Period('1/2016')

Period('2016-01', 'M')

In [7]:
pd.Period('3/5/2016')

Period('2016-03-05', 'D')

You can perform arithmetic on Periods. For example, adding 5 to a monthly period advances it by 5 months.

In [8]:
pd.Period('1/2016') + 5

Period('2016-06', 'M')

### DatetimeIndex and PeriodIndex

When we use Timestamps as the index of a Series or DataFrame, pandas automatically creates a `DatetimeIndex`.

In [9]:
t1 = pd.Series(list('abc'), [pd.Timestamp('2016-09-01'), pd.Timestamp('2016-09-02'), 
                             pd.Timestamp('2016-09-03')])
t1

2016-09-01    a
2016-09-02    b
2016-09-03    c
dtype: object

In [10]:
type(t1.index)

pandas.core.indexes.datetimes.DatetimeIndex

Similarly, when we use Periods as the index, it becomes a `PeriodIndex`.

In [11]:
t2 = pd.Series(list('def'), [pd.Period('2016-09'), pd.Period('2016-10'), 
                             pd.Period('2016-11')])
t2

2016-09    d
2016-10    e
2016-11    f
Freq: M, dtype: object

In [12]:
type(t2.index)

pandas.core.indexes.period.PeriodIndex

### Converting to Datetime

Often, dates are imported as strings. We can use `pd.to_datetime()` to intelligently convert them into standard Timestamps.

In [18]:
d1 = ['2 June 2013', 'Aug 29, 2014', '2015-06-26', '7/12/16']

ts3 = pd.DataFrame(np.random.randint(10, 100, (4,2)), index=d1, 
                   columns=list('ab'))
ts3

               a   b
2 June 2013   74  29
Aug 29, 2014  91  39
2015-06-26    85  32
7/12/16       70  30

In [20]:
ts3.index = pd.to_datetime(ts3.index, format="mixed")
ts3

             a   b
2013-06-02  74  29
2014-08-29  91  39
2015-06-26  85  32
2016-07-12  70  30

If your date strings follow the European format (Day first), you can pass `dayfirst=True`.

In [21]:
pd.to_datetime('4.7.12', dayfirst=True)

Timestamp('2012-07-04 00:00:00')

### Timedeltas

`pd.Timedelta` represents a duration or difference in times. Subtracting two Timestamps yields a Timedelta.

In [22]:
pd.Timestamp('9/3/2016')-pd.Timestamp('9/1/2016')

Timedelta('2 days 00:00:00')

In [23]:
pd.Timestamp('9/2/2016 8:10AM') + pd.Timedelta('12D 3H')

C:\Users\kanko\AppData\Local\Temp\ipykernel_23636\4057865460.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version. Please use 'h' instead of 'H'.
  pd.Timestamp('9/2/2016 8:10AM') + pd.Timedelta('12D 3H')

Timestamp('2016-09-14 11:10:00')

### Date Offsets

Pandas provides date offsets for working with business calendars or specific cadences (e.g., end of the month, week).

In [24]:
pd.Timestamp('9/4/2016').weekday()

6

In [25]:
pd.Timestamp('9/4/2016') + pd.offsets.Week()

Timestamp('2016-09-11 00:00:00')

In [26]:
pd.Timestamp('9/4/2016') + pd.offsets.MonthEnd()

Timestamp('2016-09-30 00:00:00')