In [1]:
import pandas as pd
import numpy as np

In [2]:
dates = pd.date_range('10-01-2016', periods=9, freq='2W-SUN')
dates

DatetimeIndex(['2016-10-02', '2016-10-16', '2016-10-30', '2016-11-13',
               '2016-11-27', '2016-12-11', '2016-12-25', '2017-01-08',
               '2017-01-22'],
              dtype='datetime64[ns]', freq='2W-SUN')

In [3]:
pd.date_range('10-01-2016', periods=9, freq='B')

DatetimeIndex(['2016-10-03', '2016-10-04', '2016-10-05', '2016-10-06',
               '2016-10-07', '2016-10-10', '2016-10-11', '2016-10-12',
               '2016-10-13'],
              dtype='datetime64[ns]', freq='B')

In [4]:
pd.date_range('04-01-2016', periods=12, freq='QS-JUN')

DatetimeIndex(['2016-06-01', '2016-09-01', '2016-12-01', '2017-03-01',
               '2017-06-01', '2017-09-01', '2017-12-01', '2018-03-01',
               '2018-06-01', '2018-09-01', '2018-12-01', '2019-03-01'],
              dtype='datetime64[ns]', freq='QS-JUN')

In [5]:
dates = pd.date_range('10-01-2016', periods=9, freq='2W-SUN')
df = pd.DataFrame({'Count 1': 100 + np.random.randint(-5, 10, 9).cumsum(),
                  'Count 2': 120 + np.random.randint(-5, 10, 9)}, index=dates)
df

            Count 1  Count 2
2016-10-02      101      124
2016-10-16      101      124
2016-10-30       99      122
2016-11-13      101      126
2016-11-27      103      129
2016-12-11      102      123
2016-12-25       98      129
2017-01-08       96      116
2017-01-22      101      127

In [6]:
df.index.weekday

Index([6, 6, 6, 6, 6, 6, 6, 6, 6], dtype='int32')

In [7]:
df.diff()

            Count 1  Count 2
2016-10-02      NaN      NaN
2016-10-16      0.0      0.0
2016-10-30     -2.0     -2.0
2016-11-13      2.0      4.0
2016-11-27      2.0      3.0
2016-12-11     -1.0     -6.0
2016-12-25     -4.0      6.0
2017-01-08     -2.0    -13.0
2017-01-22      5.0     11.0

In [8]:
df.resample('M').mean()

C:\Users\kanko\AppData\Local\Temp\ipykernel_24404\1818180140.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.resample('M').mean()

               Count 1     Count 2
2016-10-31  100.333333  123.333333
2016-11-30  102.000000  127.500000
2016-12-31  100.000000  126.000000
2017-01-31   98.500000  121.500000

In [12]:
df['2016-12':]

            Count 1  Count 2
2016-12-11      102      123
2016-12-25       98      129
2017-01-08       96      116
2017-01-22      101      127